#############################
### Chapter 11: Exercise 3  ###
#############################

def main():

    students = {}

    # Use a space to allow for the while check below
    new_student = " "

    # Get student names
    while (new_student != ""):
        new_student = input("Student's name (or press ENTER to finish)")
        if new_student != "":
            new_grade = float(input("Grade for " + new_student + ": "))
            students[new_student] = new_grade

    # Print class roster
    print("\nClass roster:")
    for (student, grade) in students.items():
        print(student + " (" + str(grade) + ")")

    average = sum(students.values()) / len(students.values())
    print(average)

if __name__ == '__main__':
    main()



#############################
### Yahtee Studio        ###
#############################

import random
from test import testEqual

# The roll_dice function simulates the rolling of the dice. It
# creates a 2 dimensional list: each column is a die and each
# row is a throw. The function generates random numbers 1-6
# and puts them in the list.
def roll_dice(num_dice, num_rolls):

    # create a two-dimensional (num_dice by num_rolls) of zeros
    double_list = [[0 for i in range(num_dice)] for j in range(num_rolls)]

    # loop through each row and column, filling it with a random roll
    for roll in range(0, len(double_list)):
        for die in range(0, len(double_list[roll])):
            double_list[roll][die] = (int)(random.random()*6 + 1)

    return double_list


# This function takes a 2D list (which can be generated by roll_dice)
# and sums the value of all the dice in each row. It returns a 1
# dimensional list with the sum of each throw.
# Example:
# double_list: [[1, 5, 6],[2, 3, 1],[1, 3, 3]]
# sum_of_roll should return: [12, 6, 7]
def sum_of_roll(double_list):

    num_rolls = len(double_list)
    num_die = len(double_list[0])
    sums = [0 for i in range(num_rolls)]

    for roll in range(0, num_rolls):
        for die in range(0, num_die):
            sums[roll] += double_list[roll][die]

    return sums

# Bonus function! Takes a 2D list and returns
# the number of times a person rolls Yahtzee (all dice have
# the same value). Hint: you may want to create a helper
# function that takes individual rows of the list.
def yahtzee(double_list):

    num_yahtzees = 0

    for roll in double_list:
        if roll_is_yahtzee(roll):
            num_yahtzees += 1

    return num_yahtzees

def roll_is_yahtzee(a_list):
    
    is_yahtzee = True
    first_die = a_list[0]

    for die in a_list:
        # If we still have a potential yahtzee, check the next die
        is_yahtzee = (is_yahtzee and (die == first_die))

    return is_yahtzee
